<html>
<head>
<title>登陆页</title>
</head>
<body>
	<p><?php echo $text; ?></p>
请输入用户名和密码
  <form method="get" action="">
  	<input type="hidden" name="url" value="<?php echo $url; ?>" >
  <p>姓名：<input type="text" name="name" size="10"></p>
  <p>密码：<input type="password" name="passwd" size="10"></p>
  <p><input type="submit" value="确定">
     <input type="reset" value="取消"></p>
  </form>
  </body>
</html>